### ISSUE TITLE
Static non-random monthly reward without having to edit nbt of each month

### ISSUE THREAD

**Issue by LyndaFox** [MarkusBordihn/BOs-Daily-Rewards#12]
Wondering if there is a way/plan to make the daily rewards per month statics per day as we want to balance the daily reward monthly ourself and keeping it the same every month. We know that we can edit the daily reward nbt ourself but we might not be able to set it through nbt editor first thing on the first day of next month everytime. The mod is working great so far except for that it randomize our 31 item list.

**Comment by MarkusBordihn** [comment]
Thanks for the feedback. Could you please share an example configuration with me, because normally if you have the same or higher amount of needed items for a month it should take the order of the list 1:1 without any randomization or adding additional items.

See: https://github.com/MarkusBordihn/BOs-Daily-Rewards/blob/f321752d547d2bd51b1233dadbd132ea0ae6e1dd/src/main/java/de/markusbordihn/dailyrewards/rewards/Rewards.java#LL71C3-L71C3

If this is not working, it looks like a bug which I need to check more in detail. Thanks.

**Comment by LyndaFox** [comment]
Ah for clarification, the items themself are not randomized but shuffled by date compared to the code order in config.
![image](https://user-images.githubusercontent.com/70683057/221419505-46328fbe-ef6e-4f41-a8c6-4583177d5439.png)
![image](https://user-images.githubusercontent.com/70683057/221419534-5f3bb2b9-dd1c-4b08-b47c-2de4002c7493.png)

**Comment by MarkusBordihn** [comment]
Thanks looks like a bug. Could you let me know which Minecraft version you are using to replicate this issue on my side?

**Comment by LyndaFox** [comment]
Minecraft version: 1.19.2
Mod version: daily_rewards_1.19.2-3.7.0

**Comment by MarkusBordihn** [comment]
Thanks for the details. So in this case it's not a bug, because your list only includes 26 items instead of 28 items which would be need for the month to use it without any fill items.

But anyways I added two new config options like `useFillItems` and `shuffleRewardsItems` which should cover your use-cases.

- If you setting `shuffleRewardsItems` to `false` all fill items will be append your pre-defined list.
- If you disable the fill items complelty you need to make sure to provide a items for each day of the month (more items than days are fine).

The updated version should be live in the next hours.
