### ISSUE TITLE
Can't edit Config using "In-Game Config Editor Mods"

### ISSUE THREAD

**Issue by Rageouss** [MarkusBordihn/BOs-Daily-Rewards#15]
**Describe the bug**
This feels like a Bug considering you can access all the Proper Config Options for Daily Rewards, yet you can't hit apply after adding a new reward. 

I've tested without any success with the TWO most Popular "n-Game Config Editor" MODS
 
1. Configured: https://www.curseforge.com/minecraft/mc-mods/configured

2. https://www.curseforge.com/minecraft/mc-mods/gamemenumodoption

**To Reproduce**
1. Download the Configured MOD, Game Menu Mod Option, or both along with the "Daily Rewards" MOD.

2. Click on the 'MODS' option in Minecraft's Main Menu and on the left hand side choose the Daily Rewards MOD which will show another screen called "Client Configurations" for Daily Rewards. Then click "Modify>Fill Items" and then try to add a new Daily reward.

3. For example you can try "minecraft:diamond" and then try to click "Apply" and it won't allow you to add the item which is the issue

 
**Expected behavior**
It should allow you to hit apply and successfully add the item you want to add. Out of HUNDREDS of MODS that I've edited configs for this is the first time that I've never been able to edit one.  

**Screenshots**
![2023-09-10_03 21 39](https://github.com/MarkusBordihn/BOs-Daily-Rewards/assets/64507792/18fc92d7-1073-48fa-bc3c-d1f219a4b245)

**Debugging**
I went through comments on the CurseForge Page, checked other issues here on Github, and also tried to Google it. I wasn't able to find anything. 

**Is the issue happening in combination with other mods? (If yes, please provide a full list)**

Example 1:
- **Daily Rewards**
-  **Configured:** https://www.curseforge.com/minecraft/mc-mods/configured

Example 2:
- **Daily Rewards**
- **Game Menu Mod Option:** https://www.curseforge.com/minecraft/mc-mods/gamemenumodoption

NOTE: Only test with one "In-Game Config Editor Mods" installed at a time.

**Comment by MarkusBordihn** [comment]
Thanks for the report and even if you were able to edit the config file with such tools it will not help you so much.

There are three kind of config files:

1. Client config (client only)
2. Common config (server and client)
3. Server config (server only)

A common config like in this case needs to be adjusted on the client and server with the exact same content, otherwise some feature will not working as expected.

This mean such config mod will not be able to adjust the config on the server and client on the same time and you would still need to copy and paste the config file between the client and server.
This is also mentioned by the configured mod if self, see: `... Supports editing client, common and server configurations (client files only).`

Furthermore for most modifications for this mod you need to restart the server to taking them into consideration.

I'm not sure why configured is not working for the lists but for other options, but this is something which needs to be checked by MrCrayfish the configured author more in detail.

**Comment by Rageouss** [comment]
I have already reached out and they said considering the amount of Downloads they have and how there is one universal way to do it that the problem is with Daily Rewards and how it's setup. 

Regarding what you said about about editing the files and needing copies I understand, but this is easier and more efficient in setting up the rewards exactly how you want them on the go and when happy with them just copy the configs to the server. 

I have a way of reloading the configs mid in-game so I don't have to restart. It works as I've tested it by manually editing the configs files, reloading, and seeing my changes. 

Additionally, most MODS these days reload with the MC command /reload

**Comment by Rageouss** [comment]
I'm sorry, I don't feel this issue should be closed yet.

**Comment by MarkusBordihn** [comment]
First of all thanks for the feedback. 

Is there a official issue report or link were I could see their feedback like: `... considering the amount of Downloads they have and how there is one universal way to do it that the problem is with Daily Rewards and how it's setup.`

I'm using the official Forge Config system for my config files, without any core modding or mixin which is clearly visible at:
https://github.com/MarkusBordihn/BOs-Daily-Rewards/blob/1.20.1/src/main/java/de/markusbordihn/dailyrewards/config/CommonConfig.java

Which mean if this is an official and visible response from their side, I'm happy to check this directly with them.
Otherwise there is not a lot I could do in this case, if they are unwilling to check the issue / maybe edge-case from there side more in detail.
