### ISSUE TITLE
[Suggestion] A way to give different rewards to certain players

### ISSUE THREAD

**Issue by Illios42** [MarkusBordihn/BOs-Daily-Rewards#3]
**Is your feature request related to a problem? Please describe.**
It is not, just something that could be very useful for servers with donator rank(s); Enabling a player or a group to have different rewards or allowing only them to claim some days. We'd like to use the system to both give out items for everyone to use and also unobtainable things only for the donators as a perk.

**Describe the solution you'd like**
A way to differentiate who gets/can claim what reward, maybe through a permissions mod like Luck Perms? If that is possible lol

**Describe alternatives you've considered**
/

**Additional context**
Nothing really, it's a very nice and simple concept otherwise!

**Comment by MarkusBordihn** [comment]
Interesting idea. The easiest way would be to using loot bags and defining different lot tables for the different kind of groups.

Otherwise I see the following two possibilities which should be easy to implement:

1. I could offer some kind of "loot bag" each 7 days, which could be defined over loot tables or so more in detail.
2. I creating two types of reward definition and the user could be assigned over the config to one or the other (not both) to get different rewards during the month.

Please let me know which options you are preferring.
 
Keep in mind that the donation items should be only cosmetic items and nothing which gave's them an advancement over the normal player.

**Comment by Illios42** [comment]
First off, I totally agree with you; The items should only be cosmetic. Our idea was to give out player heads for our donators for decoration; The amount of heads you can get each month varying by your donation rank. (This idea was born before we found this super fitting mod btw). Play to win > Pay to win, all the way.

I gathered some feedback from our owner and he was definitively in favor of option two, solely to provide more flexibility on what we can offer for donators throughout the whole month, not just one day. Though we do have some suggestions to add onto; 
The main one would be to allow assigning of the groups via a permission handling mod like Luck Perms and FTB Ranks (the two common ones used for forge in our experience) instead of config, for automatically adding the rewards once the required role was given and for being able to work with a lot of players very easily. Basically, integration of said mods.

There's also a another reason, which plays right in with our second suggestion; 
Upping the amount of reward definitions from two so you can customize for multiple groups (like if you have different levels of a rank like we do). With the combined support for a permission handling mod, you could have a unique reward for each of your permission groups if you really needed it and it'd be easy and quick to apply after configuration.

On a side note, it's great to see you take feedback and I hope we can work sth out

**Comment by MarkusBordihn** [comment]
I don't know if this is this relevant but I restructured the complete mod and the new beta version includes a feature which could be used for something like this.

When I fixed all remaining issues in the beta version I will add config to allow to limited the "special" rewards to specific players.
